#!/usr/bin/perl

use strict;
use warnings;

use File::Basename;
use lib dirname($0);

use Pplight;

for (@ARGV) {
    my $h = Pplight->new($_);
    my $ig = $h->include_guard() // '(none)';
    printf "%-40s\t%s\n", $_, $ig;
}
